# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Liveboard < Formula
  desc "Markdown-powered Kanban board with real-time collaboration"
  homepage "https://github.com/and1truong/liveboard"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/and1truong/liveboard/releases/download/v0.11.0/liveboard_0.11.0_darwin_amd64.tar.gz"
      sha256 "0f018508618951f51b2012d68bfb30fab97da375093487b49fa5a4e64f69afc0"

      define_method(:install) do
        bin.install "liveboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/and1truong/liveboard/releases/download/v0.11.0/liveboard_0.11.0_darwin_arm64.tar.gz"
      sha256 "bd5a2654c19ab8cd502fe8f257044512e4a8d8677df99ae8d70bb41fc4258bbf"

      define_method(:install) do
        bin.install "liveboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/and1truong/liveboard/releases/download/v0.11.0/liveboard_0.11.0_linux_amd64.tar.gz"
      sha256 "043437c2ff8bfcc62ee34f662d5d3c94154e97a2992af2d23355e52fe989adc3"
      define_method(:install) do
        bin.install "liveboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/and1truong/liveboard/releases/download/v0.11.0/liveboard_0.11.0_linux_arm64.tar.gz"
      sha256 "82acd7732b70a37bf894ee6b6c39b72b9c75f9f12df51656e40ba1d89ccf90ed"
      define_method(:install) do
        bin.install "liveboard"
      end
    end
  end
end
