# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Liveboard < Formula
  desc "Markdown-powered Kanban board with real-time collaboration"
  homepage "https://github.com/and1truong/liveboard"
  version "0.11.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/and1truong/liveboard/releases/download/v0.11.6/liveboard_0.11.6_darwin_amd64.tar.gz"
      sha256 "68a0b6f0c4ec5d68e2058b590e91bcfd49e09d168b2ebcf0cbe56746a59f88f2"

      define_method(:install) do
        bin.install "liveboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/and1truong/liveboard/releases/download/v0.11.6/liveboard_0.11.6_darwin_arm64.tar.gz"
      sha256 "0eb258cd3a7fb5d47859ad616d380ad0c14b7d79f925e768d21bf0dc6a6e06b4"

      define_method(:install) do
        bin.install "liveboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/and1truong/liveboard/releases/download/v0.11.6/liveboard_0.11.6_linux_amd64.tar.gz"
      sha256 "4236a92b7eb2842825e332e24e91c70c401a37da53c98bd0bb3d4851921d84f5"
      define_method(:install) do
        bin.install "liveboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/and1truong/liveboard/releases/download/v0.11.6/liveboard_0.11.6_linux_arm64.tar.gz"
      sha256 "96b3b4cb2d1bae28afcca8fcedcbd874467c2256937a63348c1b9c5ec79f01af"
      define_method(:install) do
        bin.install "liveboard"
      end
    end
  end
end
